name: On Pull Request

on: pull_request

jobs:
  build_linux_gcc:
    name: Build on Linux with GCC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          set -x
          mkdir Release
          cd Release
          cmake -DBOOST_ROOT=$BOOST_ROOT_1_69_0 -DBoost_ARCHITECTURE=-x64 -DBINLOG_FORCE_TESTS=ON ..
      - name: Build
        run: |
          cd Release
          make -j2 VERBOSE=1
      - name: Test
        run: |
          cd Release
          ctest -VV

  build_linux_gcc_asan:
    name: Build on Linux with GCC+ASAN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          set -x
          mkdir AddressSanitized
          cd AddressSanitized
          cmake -DBOOST_ROOT=$BOOST_ROOT_1_69_0 -DBoost_ARCHITECTURE=-x64 -DBINLOG_FORCE_TESTS=ON -DBINLOG_USE_ASAN=On ..
      - name: Build
        run: |
          cd AddressSanitized
          make -j2 VERBOSE=1
      - name: Test
        run: |
          cd AddressSanitized
          ctest -VV

  build_linux_gcc_tsan:
    name: Build on Linux with GCC+TSAN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          set -x
          mkdir ThreadSanitized
          cd ThreadSanitized
          cmake -DBOOST_ROOT=$BOOST_ROOT_1_69_0 -DBoost_ARCHITECTURE=-x64 -DBINLOG_FORCE_TESTS=ON -DBINLOG_USE_TSAN=On ..
      - name: Build
        run: |
          cd ThreadSanitized
          make -j2 VERBOSE=1
      - name: Test
        run: |
          cd ThreadSanitized
          ctest -VV

  build_on_linux_clang_tidy:
    name: Build in Linux with Clang+Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          # remove broken packages installed by default
          sudo apt-get remove -y clang-6.0 libclang-common-6.0-dev libclang1-6.0 libllvm6.0
          sudo apt-get install -y clang clang-tidy
      - name: Configure
        run: |
          set -x
          mkdir Clang
          cd Clang
          export CC=$(which clang)
          export CXX=$(which clang++)
          cmake -DBOOST_ROOT=$BOOST_ROOT_1_69_0 -DBoost_ARCHITECTURE=-x64 -DBINLOG_FORCE_TESTS=ON -DBINLOG_USE_CLANG_TIDY=On ..
      - name: Build
        run: |
          cd Clang
          make -j2 VERBOSE=1
      - name: Test
        run: |
          cd Clang
          ctest -VV

  # do not test on macOS: boost is not installed,
  # installing it from brew takes too long
  build_mac_clang:
    name: Build on macOS with Clang
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir Release
          cd Release
          cmake ..
          make -j2 VERBOSE=1

  build_win_msvc:
    name: Build on Windows with MSVC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir Release
          cd Release
          cmake -DBINLOG_FORCE_TESTS=ON ..
      - name: Build
        run: |
          cmake --build Release --config Release -j2
      - name: Test
        run: |
          $Env:path += ";${env:BOOST_ROOT}\lib"
          cd Release
          ctest -VV -C Release
