name: On Pull Request

on: pull_request

jobs:
  build_linux_gcc:
    name: Build on Linux with GCC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir Release
          cd Release
          cmake ..
          make -j2 VERBOSE=1
      - name: Test
        run: |
          ctest -VV

  build_linux_mac:
    name: Build on macOS with Clang
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir Release
          cd Release
          cmake ..
          make -j2 VERBOSE=1
      - name: Test
        run: |
          ctest -VV
